koki-takishita/home-care-navi-api

app/models/user.rb, config/application.rb
1. `app/mode/user.rb`内、deviseの`trackable`の無効化 
```ruby
class User < ActiveRecord::Base
devise :database_authenticatable, :recoverable,
:validatable, :registerable, :omniauthable
:trackable
include DeviseTokenAuth::Concerns::User
end
```
[Qiita::削除した背景](https://qiita.com/terufumi1122/items/d5530bc87689d886dee8)
[stackOverFllow::より詳しい説明や理由](https://stackoverflow.com/questions/33008187/devise-error-undefined-method-current-sign-in-ip)
2. middleware追加 セッションを維持してくれない
```ruby
module Api
class Application < Rails::Application
config.load_defaults 7.0
config.i18n.default_locale = :ja
config.time_zone = 'Tokyo'
config.active_record.default_timezone = :local
config.api_only = true
config.middleware.use ActionDispatch::Session::CookieStore
end
end
```
画面からはできない・まだPOSTMANのみ
APIを直接叩けばログイン処理ができる
- …
=> postmanからログイン・ログアウト処理ができる

Gemfile, Gemfile.lock, app/models/office.rb, db/migrate/20220510060242_create_offices.rb, db/migrate/20220516091139_rename_holiday_to_flags_in_offices.rb, db/seeds.rb
- gem flag_shih_tzu https://rubygems.org/gems/flag_shih_tzu
- 実装手順で参考にした記事　https://weseek.co.jp/tech/819/
```
この定義した数字を足し合わせていくことで、事業所がいつ休業日なのかを表す。
1  日曜日
2  月曜日
4  火曜日
8  水曜日
16  木曜日
32  金曜日
64  土曜日
```
* 機能フラグ(Feature Flag)を追加し営業日の各フラグを制御した
* なし
* なし
* なし
- dockerコンテナを消して再ビルドする
`docker-compose build`
* カラム名を変更したので、`rails:db:migrate`を実行する
```
```
* `rails:db:seed`でダミーデータを作る
* flagsの値が加算されているか確認
```
> Office.find(1)
id: 1,                                                                          
flags: 9, …
```
=> build: install gem FlagShifTzu 営業日フラグ制御

app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb
@watasho358 @koki-takishita @tmhr0 
[link](https://dev.classmethod.jp/articles/pull-request-template/)
* https://example.com
* ケアマネの新規登録をするとケアマネ用の認証メールが届く
*なし
ケアマネージャーの新規登録のリクエストを送るとケアマネージャー用のメールが届く
なし
**カスタマー(customer)**
・動画
https://www.loom.com/share/d09d945c83e246b4adc5185b40d5c1b7
1.localhost:3000/api/usersにリクエスト送る
```
name: 任意
email: 任意
password: password
password_confirmation: password
post_code: 任意
address: 任意
phone_number: 任意
confirm_success_url: localhost:8000
```
2.メールキャッチャーにカスタマーと書かれたメールが飛んでくる
・PostmanからPost localhost:3000/api/users　にリクエストを送る
https://gyazo.com/56578c3cb5d9c870bd0091e0e2047aeb
・メールキャッチャーにカスタマーと書かれたメールが飛んでくる
https://gyazo.com/62b81d9541b0db91aaa4f500f390892d
**ケアマネ(specialists)**
・動画手順
https://www.loom.com/share/3dda126c119542e9b34eca7a3006c795 …
=> add：specialists-mail

db/migrate/20220517052740_add_selected_flags_to_offices.rb
* 休業日の曜日を格納するカラムを追加
* なし
* なし
* なし
- 事業所のデータがある場合、削除
```
> Office.destroy.all
```
* `rails db:migrate`後、`rails db:migrate:status`
```
--------------------------------------------------                
up     20220509013022  Devise token auth create users          
up     20220509083245  Add user type to users                  
up     20220510060242  Create offices                          
up     20220517052740  Add selected flags to offices　  ← NEW！
```
- `rails db:seed` 実行（3人分のユーザが作られていることが前提）
- 選択済みの休業日を確認。find()には事業所のIDが入ります。
```
> Office.find(1).selected_flags
Office Load (7.6ms)  SELECT "offices".* FROM "offices" WHERE "offices"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]] …
```
=> build: 休業日の曜日を格納するカラムの追加

app/controllers/api/specialists/staffs_controller.rb, config/routes.rb
* スタッフ登録機能（画像抜き）
* バリデーション（画像以外はフロント側で完結。）
* 画像登録（次のプルリク確認時間16:00までに間に合えば、追加でコミットし、伝えます。）
* スタッフの画像以外の情報をDBに保存できる
* 画像の登録
- fetch後、checkout
```
$ git fetch
$ git ch origin/feature/スタッフ登録機能-画像抜き
```
- PostmanでPostリクエストを送る
https://www.postman.com/
```
【コピペ用】
http://localhost:3000/api/specialists/staffs
name  田中
kana  たなか
introduction  自己紹介
```
* `"status": "success"`と表示されているか確認
- コンソール上でスタッフが登録されているか確認
```
$ docker-compose exec web bash
> Staff.all
Staff Load (5.1ms)  SELECT "staffs".* FROM "staffs"
=>                                                               
[#<Staff:0x0000ffff993a2c28                                      
id: 1,                                                         
office_id: 1,                                                  
name: "田中", …
```
=> build: スタッフ登録(画像抜き)

config/routes.rb
[API一覧](https://docs.google.com/spreadsheets/d/1sJ_ZjXjCdBJkpl0gbS_HX3wDeZhihUoqddtIrHCPFnY/edit#gid=0)
1. loginのエンドポイントAPI定義書どおりに修正
**左:変更前 右:修正後**
```ruby
api/users/sign_in → api/login
```
2. logoutのエンドポイントAPI定義書どおりに修正
```ruby
api/users/sign_out → api/logout
```
フロントには未対応
エンドポイントが、定義書通りになる
フロントのパスをいじってないので、フロント側からログインはできなくなる
1. 手順動画の手順で確認 **エンドポイント変わるので注意**
```ruby
http://localhost:3000/api/logout
email
password
```
[手順動画](https://www.loom.com/share/f4a1eb32b51841499ad85c9c4d2710ba)
* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）
=> fix: ログイン・ログアウトルーティング修正

app/controllers/api/specialists/staffs_controller.rb, app/models/staff.rb, config/environments/development.rb
* スタッフ登録機能（画像あり）
* フロントから渡ってきた画像をローカルストレージに保存（storageフォルダに画像のメタデータが保存されます）
* モデルにメソッドを定義し画像のURLを発行・JSONで返す
* 事業所ごとのスタッフを取得（今週は対応しない）
* S3へのアップロード（今週対応予定）
* 画像のリサイズ（必要に迫られたときに来週以降対応）
* スタッフの画像が登録できるようになる
* なし
- fetch後、checkout
```
git fetch
```
```
git checkout origin/feature/スタッフ登録-画像あり
```
* [https://github.com/koki-takishita/home-care-navi-front/pull/83](https://github.com/koki-takishita/home-care-navi-front/pull/83)  　こちらの動作確認ですべて完結するようになっています
コンソールでも画像が保存できているか確認できます。
- docker内に入り、コンソールに入る
```
docker-compose exec web bash 
```
```
rails c
```
- スタッフの情報を全件取得し、目的のデータの画像データを取得する
```
> Staff.all
〜　findでID指定して検索します。ファイル名やバイトサイズなどの情報を取得できます　〜
> Staff.find(1).image_blob
（中略）                                                                
=> …
```
=> build: スタッフ登録-画像あり

.gitignore, app/controllers/api/offices_controller.rb, app/controllers/api/specialists/offices_controller.rb, app/controllers/api/specialists/staffs_controller.rb, app/models/office.rb, app/models/specialist.rb, app/models/staff.rb, app/models/user.rb, config/locales/ja.yml, config/routes.rb, db/migrate/20220511080656_create_contacts.rb, db/schema.rb, db/seeds.rb
- スペシャリスト・スタッフ・事業所の関連付け
- seedでユーザー・スペシャリストを作成できるようにした
- 事業所テーブルのcreateメソッド作成・ActiveStorage紐付け
- スタッフコントローラindexメソッド修正
- 事業所詳細 事業所画像取得 
- 事業所・スタッフをseedで作成すること
- 事業所登録ができるようになる
- なし
```ruby
git fetch && git checkout origin/feature/office_create
```
- コンテナ入る
```ruby
```
- seed 実行
```ruby
rails db:seed
```
- ユーザー・スペシャリストのデータ確認
```
User.all
```
- ケアマネでログインし、事業所登録画面で事業所登録をすませる
https://github.com/koki-takishita/home-care-navi-front/pull/126
- Headers
```ruby
client
expiry
uid
access-token
```
- 事業所登録後、コンソールに入って事業所のIDを確認する
```
rails c
Office.all
```
```ruby
http://localhost:3000/api/offices/<事業所ID>
```
[Postman 手順動画](https://www.loom.com/share/f72a6b5bc3284ea2bf58a119fdec290b)
- 確認してほしいシナリオテスト
8.5 事業所詳細画面に行く …
=> 事業所登録機能　スタッフコントローラindexメソッド修正

app/controllers/api/overrides/customer/sessions_controller.rb, app/models/user.rb, config/initializers/cors.rb
1.ケアマネージャーログイン後のヘッダーレイアウト
2.ログイン時事業所を持っていれば、事業所編集を表示。持っていなければ、事業所登録を表示
* ヘッダーのリンクの遷移先（各担当の方設定お願いします）
* レイアウトがすっきりしてみやすくなる
* 事業所を登録してないときは登録が表示されて、登録してる時は編集が表示される
* 特になし
- ドッカーリスタート
```ruby
docker compose restart
```
```ruby
git fetch && git checkout origin/feature/specialists_login
```
```ruby
git fetch && git checkout origin/feature/specialist-header
```
1,rails db seedを実行
2,ケアマネログインページ `http://localhost:8000/specialists/login`からログイン
```
メールアドレス　specialist@example.com
パスワード　password
```
3.メニューを開き『事業所登録』があることを確認
4.事業所を登録
5.ログアウト
6.再度ログイン
7.メニューを開く
8.事業所を登録したので、メニューを開く事業所編集になっている
[手順動画](https://www.loom.com/share/c850f23300cc4898b17784a729794ed4)
フロントとAPI合わせて確認お願いします
=> ログイン後のヘッダー編集

app/controllers/api/overrides/customer/sessions_controller.rb
存在しないユーザーがログインしようとする時に『サーバー側のエラーです』と表示されてしまうバグの修正を行なった
* 存在しないユーザーがログインしようとすると『ログイン用の認証情報が正しくありません。再度お試しください。』と表示される
- fetch and checkout 
```ruby
git fetch && git checkout origin/suwonkun-patch-1
```
手順1.`http://localhost:8000/specialists/login`に移動
手順2.フォームに存在しない値入力
手順3.『ログイン用の認証情報が正しくありません。再度お試しください。』と表示される
以前
https://gyazo.com/dc8f19d447fea12ef555fd3317482f49
編集後
https://gyazo.com/7ea0870b625e312575ef144d38e4c4c5
* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）
=> 存在しないユーザーがログイン時のエラー修正

.github/PULL_REQUEST_TEMPLATE.md, app/controllers/api/appointments_controller.rb, app/models/appointment.rb, config/routes.rb, db/migrate/20220620125926_change_appointments_meet_date_to_date.rb, db/schema.rb
- 面談希望日時をstring型からdate型に変更
- ユーザーの予約履歴を返すindexメソッド実装
- 予約履歴がないときにメッセージを返す（フロントで制御）
- ユーザーの予約履歴が見れる
- なし
```ruby
git fetch && git checkout origin/feature/appointments_index
```
- コンテナリスタート
```ruby
```
- コンテナ入る
```ruby
```
- コンソール入る
```ruby
rails c
```
- 予約のデータをすべて消す
```ruby
Appointment.destroy_all
```
- コンテナ内に戻り、マイグレーション実行
```ruby
```
- マイグレートのステータス確認
```ruby
```
```ruby
Status   Migration ID    Migration Name                               
--------------------------------------------------                     
up     20220509013022  Devise token auth create users               
up     20220509083245  Add user type to users                       
up     20220510060242  Create …
```
=> ユーザーの予約履歴を返す

app/controllers/api/appointments_controller.rb
- 予約履歴のAPIで、事業所に紐づくスタッフも取得するようにした
- なし
- フロントでスタッフ数をカウントできる
- なし
```ruby
git fetch && git checkout origin/feature/appointments_index
```
- Postmanで予約履歴を取得する。スタッフが取得できているか確認する
```ruby
localhost:3000/api/appointments
```
=> 【修正】予約履歴APIでスタッフも取得する

app/controllers/api/offices/appointments_controller.rb, app/controllers/api/specialists/appointments_controller.rb, config/routes.rb
- 予約の連絡済みかどうかのステータスの更新機能
- なし
- フロントからリクエストが正しく送られてくれば、連絡済みかどうかステータスが変わる
- なし
```ruby
git fetch && git checkout origin/feature/appointments-status-update
```
```ruby
git fetch && git checkout origin/feature/appointments_status_update
```
- APIでの動作確認は必要なし。こちらのプルリクの動作確認手順ですべて完結します。
https://github.com/koki-takishita/home-care-navi-front/pull/156
[API 一覧](https://docs.google.com/spreadsheets/d/1sJ_ZjXjCdBJkpl0gbS_HX3wDeZhihUoqddtIrHCPFnY/edit#gid=0)
=> 予約状況確認 updateメソッド実装

config/initializers/cors.rb
- テストサーバー(**localhost:9000**)からaxios通信をできるようにした
```ruby
git fetch && git checkout origin/test/set-testServer-cors
```
- コンテナリスタート
```ruby
```
- コンテナリスタートまで行ったら、こちらのプルリクを確認してください
https://github.com/koki-takishita/home-care-navi-front/pull/162
=> テストサーバー cors設定

Gemfile, Gemfile.lock, app/controllers/api/offices_controller.rb, db/dummy_files/dummy.csv, db/seeds.rb, db/seeds/dummy_office.seeds.rb
1. officeのシードデータ作成
2. officeのバリテーションルール変更
3. seedの管理を楽にしてくれるgem導入
user_idがnilのオフィスに対して、ケアマネを登録するような機能
- 本物っぽいダミーデータを作成できる
- シードファイルを複数もてるようになる
- なし
```ruby
git fetch && git checkout origin/feature/crate-dummy
```
```ruby
docker compose down
docker build
docker compose up -d
docker compose exec web bash
rails db:seed:dummy_office
rails c
Office.count
=> 50??
```
[gem url](https://github.com/james2m/seedbank/)
下記公式の内容をそのまま持ってきてますが、これが全てですので使用する時は参照してください。  
このgemの入れることで、特定のseedファイルのみ実行することができるようになります。  
例えばテストのときだけ使うアカウントを定義できたりできるかもしれません
```linux
rake db:seed                    # Load the seed data from db/seeds.rb, db/seeds/*.seeds.rb and db/seeds/ENVIRONMENT/*.seeds.rb. ENVIRONMENT is the current environment in Rails.env.
rake db:seed:bar                # Load the seed data from …
```
=> 5000のダミーオフィスを作成できる seedデータ

app/controllers/api/appointments_controller.rb, app/controllers/api/specialists/appointments_controller.rb, db/seeds.rb
- 予約データの並び替え
- 予約履歴では、予約した日時順
- 予約状況確認画面では、未連絡のものが先頭に来る
- 予約のseedの見直し
- なし
```ruby
git fetch && git checkout origin/feature/appointments-sort
```
```ruby
git fetch && git checkout origin/feature/appointments-sort
```
- コンテナ入る
```ruby
```
- seed実行（rails:db:seedでも問題ないですが、今回は5000件のオフィスがなくても動作確認できるため、スピード優先で下記のコマンドを使用します）
```ruby
rails db:seed:original
```
- ターミナルにこのように表示されればOK
```ruby
.
.
Appointmentsサンプルデータ作成完了
作成した予約数 25
.
.
```
- こちらのプルリクを確認お願いします
https://github.com/koki-takishita/home-care-navi-front/pull/172
- レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）
=> build: 予約データの並び替え 予約seed修正

app/controllers/api/customer/bookmarks_controller.rb, app/models/bookmark.rb, app/models/office.rb, app/models/user.rb, db/migrate/20220706024811_create_bookmarks.rb, db/schema.rb
- ブックマークコントローラ・モデル・マイグレーション作成
- なし
```ruby
git fetch && git checkout origin/feature/create-bookmark-table
```
- コンテナ入る
```ruby
```
- マイグレート実行
```ruby
```
- マイグレート状態を確認
```ruby
```
```ruby
database: api_development
up     20220517052740  Add selected flags to offices
up     20220518035139  Create staffs
up     20220518050442  Create active storage tablesactive storage
up …
```
=> ブックマークコントローラ・モデル・マイグレーション作成

app/controllers/api/customer/bookmarks_controller.rb, config/routes.rb, spec/factories/bookmarks.rb, spec/requests/api/customer/bookmarks_spec.rb
- ブックマーク登録 解除機能実装
- ブックマークのrequest spec作成
- なし
```ruby
git fetch && git checkout origin/feature/bookmark-create-destroy
```
```ruby
git fetch && git checkout origin/feature/submit-destroy-bookmark
```
1. Docker内に入る
```ruby
```
2. テストを実行する
```ruby
bundle exec rspec spec/requests/api/customer/bookmarks_spec.rb --format documentation
```
実行結果
```ruby
Api::Customer::Bookmarks
ログイン済み
カスタマー
ブックマークを登録できる
ケアマネ
ブックマークを登録できない
ログインしていない
ブックマークを登録できない
Finished in 1.06 seconds (files took 4.02 seconds to load)
3 examples, 0 failures
```
3. すべてのテストを実行する
```ruby
bundle exec rspec spec/requests/
```
実行結果
```ruby
Finished in 2.11 seconds (files took 3.86 seconds to load)
14 examples, 0 failures
```
4. こちらのプルリクの確認をお願いします …
=> ブックマーク登録 解除機能実装

app/controllers/api/customer/offices_controller.rb
1. スタッフ紹介ページに対応できるように、jsonを目的のものになるように修正
- テスト書かない
- スタッフ紹介ページ使用できる、jsonを返すように設定
- 何ができなくなるのか？（あれば。無いなら「無し」で OK）
テストが問題ないか確認(コンテナ内で)
```ruby
bundle exec rspec spec/requests/api/
```
- 動作確認はフロントのプルリクと一緒に行う
https://github.com/koki-takishita/home-care-navi-front/pull/183
=> スタッフ紹介ページに対応できるようにjsonの形修正

spec/rails_helper.rb, spec/requests/api/customer/thanks_spec.rb, spec/support/login_support.rb
- login処理をmodule化した
- これまで直うちだったのもを直すこと
```ruby
git fetch && git checkout origin/test/create-login-module
```
- テストがパスすること
```ruby
docker-compose exec web rspec spec/requests --format documentation
```
- 実行結果が下記のようになること
```ruby
Api::Customer::Appointments
ログイン済み
カスタマー
予約を作成できる
ケアマネ
予約を作成できない
ログインしていない
予約を作成できない
Api::Customer::Bookmarks
ログイン済み
カスタマー
ブックマークを登録できる
ケアマネ
ブックマークを登録できない
ログインしていない
ブックマークを登録できない
Api::Customer::Thanks
ログイン済み
カスタマー
お礼を作成できる
ケアマネ
お礼を作成できない
ログインしていない
お礼を作成できない
Api::Specialists::Offices
ログイン済み
スペシャリスト
事業所を登録できる
カスタマー
事業所を登録できない
ログインしていない
事業所を登録できない
Api::Specialists::Staffs
ログイン済み
スペシャリスト
スタッフを登録できる
ログインしていない
スタッフを登録できない
Finished in 2.46 seconds (files took 3.67 seconds to load)
14 examples, 0 failures
```
- `requests/***/***_spec.rb` …
=> ログインモジュール化

app/controllers/api/customer/histories_controller.rb, app/controllers/api/customer/offices_controller.rb, config/routes.rb, db/schema.rb
- 閲覧履歴のindex create updateアクション実装
- なし
```ruby
git fetch && git checkout origin/feature/create-history-index-create-update
```
```ruby
git fetch && git checkout origin/feature/request-create-update-history 
```
- こちらのプルリクを確認お願いします
https://github.com/koki-takishita/home-care-navi-front/pull/227
- [Railsでモデルのupdate_atのみを更新したい場合](https://qiita.com/ko30005/items/5d07c94fcfdf3bb75ff0)
=> 閲覧履歴のindex create updateアクション実装

app/controllers/api/specialists/thanks_controller.rb, db/schema.rb, db/seeds/dummy_thanks.seeds.rb
- ケアマネ側でお礼データ一覧を返すときに、紐付いてるオフィスとスタッフも取得していたため、仕様変更に伴い紐付けを解除
- お礼seedで名前と年齢も作成するように修正
- コミット時にテスト通らなかったためdb/schema修正
- なし
```ruby
git fetch && git checkout origin/fix/specialist-thanks-list
```
```ruby
git fetch && git checkout origin/feature/specialist-thanks-list
```
- フロントのプルリクを確認する
https://github.com/koki-takishita/home-care-navi-front/pull/229
- お礼が1件もなければお礼を作成する
- 現状のseedファイルだと1オフィス5件しか作れないので、ページネーションの動作確認のため一時的にカスタマイズする
```ruby
def create_thanks(count: 20, office: nil)
.
.
.
end
.
.
.
def create_customer_thanks
office = Specialist.first.office
create_thanks(office: office)
end
```
```ruby
docker-compose exec web rails db:seed:dummy_thanks
```
なし
- build
```ruby
docker-compose build
```
- コンテナリスタート
```ruby
```
- コンテナ入る …
=> ケアマネ側お礼コントローラ修正

spec/factories/histories.rb, spec/models/history_spec.rb
- 閲覧履歴のモデルテスト作成
- なし
```ruby
git fetch && git checkout origin/test/create-history-model-test
```
- テストを実行する
```ruby
docker-compose exec web bundle exec rspec spec/models/history_spec.rb --format documentation
```
実行結果
```ruby
Historyモデルのテスト
アソシエーションのテスト
Userモデルとの関係
N:1となっている
Officeモデルとの関係
N:1となっている
バリデーションのテスト
ユーザーidと事業所idがある場合、有効である
ユーザーidがない場合、無効である
事業所idがない場合、無効である
Finished in 1.26 seconds (files took 6.62 seconds to load)
5 examples, 0 failures
```
- [【rspec】Railsモデルテストの基本](https://qiita.com/prkrsign890/items/1b7b4af1e6d102625562)
- [【Ruby on Rails】RSpecでのモデルテスト](https://qiita.com/japwork/items/c6f58bae5e0b222e1eb0)
=> 閲覧履歴モデルテスト作成

spec/requests/api/customer/histories_spec.rb
- 閲覧履歴のリクエストスペック作成
- なし
```ruby
git fetch && git checkout origin/test/request-spec-histories
```
- 閲覧履歴のリクエストスペックの全部のテストを実行する
```ruby
docker-compose exec web bundle exec rspec spec/requests/api/customer/histories_spec.rb --format documentation
```
実行結果
```ruby
Api::Customer::Histories
ログイン済み
カスタマー
閲覧データを登録できる
閲覧データを更新できる
ケアマネ
閲覧データを登録できない
ログインしていない
閲覧データを登録できない
Finished in 1.1 seconds (files took 3.66 seconds to load)
4 examples, 0 failures
```
- なし
```javascript
NG
```
```ruby
```
```ruby
docker-compose exec web bundle exec rubocop spec/requests/api/customer/histories_spec.rb
```
=> 閲覧履歴のリクエストスペック作成

app/controllers/api/check_controller.rb, app/models/office.rb, app/models/user.rb, config/routes.rb, spec/requests/api/check_spec.rb
1. 電話番号が被りがないかチェックするapi作成
- 指定された電話番号がusesテーブルofficesテーブルに存在するかしないかを判定できる
2. リクエストスペック作成
- rubocopのリントチェック一部
新規で追加したものでなく、過去作成したロジックでエラーが出ている模様
migrateを修正する必要があるため、今回のタスクでは見送り
```ruby
❯ docker-compose exec web bundle exec rubocop app/controllers/api/check_controller.rb app/models/office.rb app/models/user.rb config/routes.rb spec/requests/api/check_spec.rb
Inspecting 5 files
.CC..
Offenses:
app/models/office.rb:13:3: C: Rails/UniqueValidationWithoutIndex: Uniqueness validation should have a unique index on the database column.
validates :user_id, uniqueness: true, allow_nil: true
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app/models/user.rb:16:3: C: Rails/UniqueValidationWithoutIndex: Uniqueness validation should have a unique index on the database column.
validates …
```
=> 指定された電話番号に被りがないか判定するapi作成

config/initializers/cors.rb
- port 5000からのアクセスを許可するように設定 heroku環境で実行できるようにするため ※ 参考サイト参照
- 開発環境で動くものを、本番でも動作するか確認したい時に使うもの
- なし
```ruby
git fetch && git checkout origin/feature/add-port-for-5000
```
- 最新のdevelop
1. フロントでコマンド実行
```ruby
yarn build && heroku local
```
2. localhost 5000にアクセスして問題なく動作するか確認する
※ リクエスト送った時にエラーでたら`cofig/`を読み込み直す必要あり
```ruby
```
**URL は該当のものに変えること**  
[API 一覧](https://docs.google.com/spreadsheets/d/1sJ_ZjXjCdBJkpl0gbS_HX3wDeZhihUoqddtIrHCPFnY/edit#gid=0)  
[ユーザーストーリー](https://docs.google.com/spreadsheets/d/1lORIuXfr7PV5dslAHE4NnRGgNqk0hJ5krfN-tV2YKq8/edit#gid=0)  
[テーブル定義書](https://docs.google.com/spreadsheets/d/15AbCnOzcFlnN8CO-sXxKM6bM …
=> port 5000を許可するように設定

app/controllers/api/customer/appointments_controller.rb, app/models/office.rb
- 予約にオフィスが紐づくようにJSONの形を修正
- 前回まではオフィスに予約が紐付いていた
- なし
```ruby
git fetch && git checkout origin/technical/fix-appointments-index
```
```ruby
git fetch && git checkout origin/technical/fix-customer-appointments-index-page
```
- こちらのプルリクを確認お願いします 👀 
https://github.com/koki-takishita/home-care-navi-front/pull/270
- [Custom JSON Rendering in Rails](https://medium.com/@tara.kelly16/custom-json-rendering-in-rails-7c68704c099e)
- methods: [:モデルのメソッド名]の使い方を参考にした
- [ifとunlessの使い分け](https://qiita.com/raamen/items/7dc9f7b89e76cc81866b)
```javascript
NG
```
```ruby
```
```ruby …
```
=> カスタマー側予約コントローラ　indexメソッド修正

app/models/staff.rb, config/locales/ja.yml, db/migrate/20220816005014_change_columns_add_notnull_on_staffs.rb, db/schema.rb, spec/models/staff_spec.rb
- スタッフテーブルのカラムにバリデーション追加
- 名前、ふりがな、紹介文にNot Null制約追加
- スタッフモデルにバリデーション設定
- 名前 ... `空文字NG、30文字まで`
- ふりがな .. `空文字NG、ひらがなの正規表現、30文字まで`
- 紹介文 ... `空文字NG、120文字まで`
- エラーメッセージ追加
- スタッフのモデルテスト作成
- なし
```ruby
git fetch && git checkout origin/test/staff-modes-test
```
- マイグレート実行
```ruby
```
```ruby
```
```ruby
```
実行結果
```ruby
database: api_development
up     20220517052740  Add selected …
```
=> スタッフモデルテスト作成 バリデーション設定

app/controllers/api/specialists/staffs_controller.rb
- スタッフのCRUDリクエストが送られたときに、成功時と失敗時でステータスコードを返すように修正
- 失敗時に返すエラーメッセージを、フロントでフラッシュメッセージが表示されるように修正
- なし
```ruby
git fetch && git checkout origin/technical/render-http_status_code-staffs_controller
```
- マージ
```ruby
git merge origin/test/staff-modes-test
```
- 先にこちらのプルリクを確認すること
https://github.com/koki-takishita/home-care-navi-api/pull/148
1. 空白文字を入れて登録する（半角・全角スペースのこと）
4. フラッシュメッセージが表示されていればOK（編集画面でも同様にエラーが出ることを確認する）
- なし
```javascript
NG
```
```ruby
```
```ruby
```
=> スタッフコントローラーでhttpステータスコード返すように設定

app/models/appointment.rb, config/locales/ja.yml, db/migrate/20220816070850_change_columns_add_notnull_and_index_to_appointments.rb, db/schema.rb, spec/factories/appointments.rb, spec/models/appointment_spec.rb, spec/requests/api/customer/appointments_spec.rb
- DBに予約テーブルの該当カラムにNot Null制約追加
- 予約モデルにバリデーション設定
- 予約モデルテスト作成
- 年齢を60歳~120歳以外のものを弾くバリデーション設定
- issueに上げています。やる予定はありません。
https://github.com/koki-takishita/home-care-navi-api/issues/151
```ruby
git fetch && git checkout origin/test/appointment-model-test
```
- マイグレート
```ruby
```
```ruby
```
```ruby
```
実行結果
```ruby
database: api_development
up     20220517052740  Add selected flags …
```
=> 予約モデルテスト作成・バリデーション設定

app/controllers/api/customer/appointments_controller.rb
- 予約作成失敗時にエラーメッセージを返す
- フロント側でステータスコードと、エラーメッセージを受け取ってフラッシュメッセージに反映されるように修正
- なし
```ruby
git fetch && git checkout origin/technical/render_error_msg-customer_appointments_controller
```
```ruby
git fetch && git checkout origin/<ここを変える>/<ここを変える>
```
- こちらのプルリクを確認お願いします
https://github.com/koki-takishita/home-care-navi-front/pull/284
- [RailsのHTTPステータスのシンボル表現](https://morizyun.github.io/ruby/rails-controller-status-code.html)
```javascript
NG
```
```ruby
```
```ruby
```
=> 予約作成失敗時にエラーメッセージを返す

spec/requests/api/customer/offices_spec.rb
- オフィスエリア検索のリクエストスペック
- キーワード検索 別のプルリクで扱う今回はエリア検索のみ
```ruby
git fetch && git checkout origin/feature/request-spec-to-office-area
```
- テストパスするか確認
```ruby
bundle exec rspec --format documentation
bundle exec rspec spec/requests/api/customer/offices_spec.rb --format documentation
```
何件取得したかを知りたかったが、`response.body`は`String`のため`count`メソッドが使えない　　
なので↓のようにJSON.parseするとhashに変換され、`count`メソッドが使えるようになる
```ruby
response.body
=> "[
"{
/"id"/: 1,
/"name"/: "/ケアパーク/"
},
{
/"id"/: 1,
/"name"/: "/老人介護ホーム佐渡/"
}
.
.
.
]"
JSON.parse(response.body)
=> [
{
id: 1
name: 'ケアパーク'
.
.
},
{
id: 2
name: '老人介護ホーム佐渡'
.
.
},
.
.
.
]
```
[動かして確認している](https://www.loom.com/share/594db5ac814e42c5a2dece0f2f40639a)
- [json parse doc](https://docs.ruby-lang.org/ja/latest/method/JSON/m/parse.html)
- …
=> オフィスエリア検索リクエストスペック

app/controllers/api/contacts_controller.rb, config/locales/ja.yml
・空白スペースで問い合わせ入力　→　確認画面で送信押すと、エラーメッセージを画面表示
・空白スペース入力で問い合わせ完了ページまで遷移できていたため、それが防止された。
- 送信ボタンPUSHでセッションストレージ破棄をしているため、
　エラー表示後に『戻る』を押しても入力していたデータはリセットされる。
```ruby
git fetch && git checkout origin/technical/contacts-valid-message-api
```
- 名前と問い合わせ内容のフォームを、空白スペースで問い合わせ入力
[確認画面にて送信ボタンPUSHし、エラーメッセージを確認](https://gyazo.com/8dd28531bc395d815db349163666d29e)
**URL は該当のものに変えること**  
なし
```javascript
NG
```
```ruby
```
```ruby
```
=> バグ改修：問い合わせ 空白登録時エラーメッセージ表示

app/controllers/api/specialists/care_recipients_controller.rb, app/models/care_recipient.rb, config/locales/ja.yml
- 空白バリデーション設定
- フロントの空白バリデーション
```ruby
git fetch && git checkout origin/fix/care_recipient_validation
```
- 利用者を空白でスペースで入力
```ruby
手順1.利用者の名前・かな・家族情報・住所をスペースで入力（登録と編集）
手順2.エラーメッセ時が表示される
```
[手順動画](https://www.loom.com/share/eb3eb5b8f8dd46e8bbdbc6ccc915d725)
**URL は該当のものに変えること**  
```javascript
NG
```
```ruby
```
```ruby
```
=> 利用者登録　空白で登録できなくする

app/controllers/api/overrides/customer/registrations_controller.rb, spec/requests/api/customer/edit_delete_spec.rb
- カスタマー編集・削除 コントローラーテスト作成
- パスワードチェックとユーザー情報編集時に、成功時のステータスコードを200が返ってくるように修正
- 以前は204(No Content)が返ってきていた
- 未ログインの状態で編集・退会ができないかテストすること
- エラーが出てしまうためテストしない
`app/controllers/api/overrides/customer/registrations_controller.rb`
```ruby
@user = User.find(current_user.id)
```
```ruby
git fetch && git checkout origin/test/customer-edit-delete
```
- テスト実行
```ruby
docker-compose exec web bundle exec rspec spec/requests/api/customer/edit_delete_spec.rb --format documentation   
```
実行結果
```ruby
Api::Customer
ログイン済みカスタマー
パスワードチェックが通る
パスワードが違うと通らない
自分の情報を編集できる
退会できる
Finished in 1.1 seconds (files took 3.91 seconds to load)
4 examples, 0 failures
```
- なし
```javascript
NG
``` …
=> カスタマー編集・削除 コントローラーテスト作成

app/models/thank.rb, config/application.rb, config/locales/ja.yml
- 従来のエラーメッセージでは意図が伝わらないため、エラーメッセージ変更
- config/local/ja.ymlのrubocop修正
修正箇所が膨大なため、別のプルリクとして実施する
```ruby
git fetch && git checkout origin/technical/thank-error-msg
```
- こちらのプルリク手順に従う
https://github.com/koki-takishita/home-care-navi-front/pull/300
**URL は該当のものに変えること**  
[API 一覧](https://docs.google.com/spreadsheets/d/1sJ_ZjXjCdBJkpl0gbS_HX3wDeZhihUoqddtIrHCPFnY/edit#gid=0)  
[ユーザーストーリー](https://docs.google.com/spreadsheets/d/1lORIuXfr7PV5dslAHE4NnRGgNqk0hJ5krfN-tV2YKq8/edit#gid=0)  
[テーブル定義書](https://docs.google.com/spreadsheets/d/15AbCnOzcFlnN8CO-sXxKM6bMS7VtExbew-FpYHav91Q/edit#gid=1771130073)
- [バリテーション、エラーメッセージフォーマットをカスタマイズする](https://zenn.dev/machamp/ar …
=> お礼同じスタッフに２回以上作成したときのエラーメッセージ変更

spec/factories/care_recipient.rb, spec/requests/api/specialist/care_recipients_spec.rb
- 利用者のCRUDテスト
```ruby
git fetch && git checkout origin/test/care_recipients-request-spec
```
- テストを実行する
```ruby
docker-compose exec web bundle exec rspec ./spec/requests/api/specialist/care_recipients_spec.rb --format documentation
```
実行結果
```ruby
Api::Specialists::CareRecipients
ログイン済み
スペシャリスト
利用者を登録できる
利用者の一覧を取得できる
利用者の詳細データを取得できる
利用者を編集できる
利用者を削除できる
ログインしていない
利用者を登録できない
Finished in 1.06 seconds (files took 2.63 seconds to load)
6 examples, 0 failures
```
- スタッフのRspec（取得時のデータ型が同じだった為）
```javascript
NG
```
```ruby
```
```ruby
```
=> APIテスト　利用者CRUD Rspec

spec/requests/api/contacts_spec.rb
- 問い合わせのリクエストテスト 1項目追加
　メールが届いているか確認
- なし
```ruby
git fetch && git checkout origin/test/contacts-mail-spec
```
- 該当ファイルのRspecテストを実施する
```ruby
docker-compose exec web bundle exec rspec spec/requests/api/contacts_spec.rb --format documentation
```
実行結果
```ruby
Api::Contacts
有効な情報
お問い合わせを登録できる
お問い合わせのメールが届いている
空の情報
お問い合わせを登録できない
Finished in 1.09 seconds (files took 4.16 seconds to load)
3 examples, 0 failures
```
[ActionMailer::Base.deliveries の実メール情報](https://gyazo.com/8bfb8e8bafa99b089fac70636bb6fd93)
[テーブル定義書](https://docs.google.com/spreadsheets/d/15AbCnOzcFlnN8CO-sXxKM6bMS7VtExbew-FpYHav91Q/edit#gid=1771130073)
- …
=> 問い合わせ　リクエストテスト　メール確認

Gemfile.lock, app/models/care_recipient.rb, spec/factories/care_recipients.rb, spec/models/care_recipient_spec.rb
- 利用者モデルテスト作成
- 利用者テーブルの各カラムに足りないバリデーション追加
-  フォーマットチェック、文字数制限
```ruby
git fetch && git checkout origin/test/care-recipient-model-test
```
- テスト実行
```ruby
docker-compose exec web bundle exec rspec ./spec/models/care_recipient_spec.rb --format documentation 
```
実行結果
```ruby
CareRecipient
アソシエーションのテスト
Officeモデルとの関係
N:1となっている
Staffモデルとの関係
N:1となっている
バリデーションのテスト
事業所id、名前、ふりがな、紹介文がある場合、有効である
事業所idがない場合、無効である
名前がない場合、無効である
名前が31文字以上の場合、無効である
ふりがながない場合、無効である
ふりがながひらがな以外の場合、無効である
ふりがなが31文字以上の場合、無効である
年齢がない場合は無効である
郵便番号がない場合は無効である
郵便番号のフォーマットが適切でない場合、無効である
住所がない場合は無効である
家族情報が31文字以上の場合、無効である
スタッフidがない場合、無効である
Finished in 0.55309 seconds (files took 2.57 seconds to load)
15 examples, 0 failures
```
[テスト仕様書](https://docs.google.com/spreadsheets/d/12xMuHo1K8Fd7FIB7rqeioxdWmrWw7aYK4 …
=> 利用者のモデルテスト

.gitignore, app/controllers/application_controller.rb, docker-compose.yml
- メールのリンククリック時リダイレクトしないバグを改修
- herokuに環境変数セット
- なし
```ruby
git fetch && git checkout origin/technical/mail-redirect-bug
```
1.  `app/controllers/application_controller.rb`内の下記の①をコメントアウト
```ruby
class ApplicationController < ActionController::API
include DeviseTokenAuth::Concerns::SetUserByToken
end
```
2. フロントの新規登録用の環境変数である`FRONT_TOP_URL`を下記のように書き換える
```js
// .env ファイル内
// before
FRONT_TOP_URL='http://localhost:8000'
// after
FRONT_TOP_URL='https://home-care-navi-v2.herokuapp.com'
```
3. nuxt側のサーバーを立ち上げ直す(環境変数を再読込させるため)
4. 新規登録処理をし、メールのリンクを踏むと下記のエラーが発生することを確認する(本番環境でも同じエラーが出ている、本番環境では画面上になにも表示されないが同じことが起きている)
[![Image from Gyazo](https://i.gyazo.com/8f7aae8484889a3d3099a73cb5461ffd.png)](https://gyazo.com/8f7aae8484889a3d3099a73cb5461ffd)
5. 原因 …
=> 新規登録のメールなど、リダイレクト処理がしないバグ改修

app/controllers/api/overrides/reset_passwords_controller.rb, app/views/devise/mailer/reset_password_instructions.html.erb, config/routes.rb, spec/requests/api/overrides/customer/reset_passwords_spec.rb
- パスワードリセットエンドポイントの共通化(customer/specialist)
- パスワードリセット機能 eidtアクション redirect時にquery含めるように修正
- rubocop一部修正: ` app/controllers/api/overrides/reset_passwords_controller.rb`
- rspec このプルリクでは書かない
```ruby
git fetch && git checkout origin/technical/password-reset-query-set
```
- fetch and checkoutruby
```ruby
git fetch && git checkout origin/technical/password-reset-404
```
- ↓動作確認手順はこちらに記述済み
https://github.com/koki-takishita/home-care-navi-front/pull/320
```javascript
NG
```
```ruby
```
```ruby
```
=> パスワードリセットのリダイレクト時はquery含めるように修正
