Gemfile
Gemfile.lock
app/controllers/api/users_controller.rb
app/models/user.rb
config/initializers/cors.rb
config/routes.rb
db/migrate/20220425180640_create_users.rb
db/migrate/20220425212659_remove_activation_digest_to_users.rb
db/schema.rb

1. docker build
`docker-compose build`
2. コンテナ立ち上げ(dockerのdesktopAppが起動していないとエラーになる)
`docker-compose up -d web`
3. コンテナの中入る(bundle installやrailsコマンドはコンテナの中で行う)
`docker-compose exec web bash` 
4. もしバンドルインストール、データ・ベースの更新を行ったら
- コンテナ停止後、削除して再度「1〜4」のコマンド実行
※事故るからむやみに変なコマンド打たない
- 基本的に使い終わったコンテナは削除する(エラーのもと)
確認方法
1. nuxtから正しいリクエストを送れば、登録処理が正常に可能である
2. postmanからも同様
3. getリクエスト、postリクエスト両方試す

バリテーションなし、新規登録機能

---

Gemfile.lock
app/models/user.rb
spec/factories/users.rb
spec/models/user_spec.rb

モデルファイルにバリデーションを設定
フォーマットの制限はまだしてません。
とりあえずは、データの有無の制限。ユニーク制約のみです。

新規会員登録モデル作成

---

app/controllers/api/offices_controller.rb
app/controllers/api/overrides/registrations_controller.rb
config/environments/development.rb
config/initializers/devise.rb
config/initializers/devise_token_auth.rb
config/routes.rb
docker-compose.yml

* 事業所コントローラ作成、route.rb修正
* バリデーション設定、テスト（5/13(金)にやる予定）
* なし
* なし
* コンソール内でルートの設定が反映されてるか確認
```
$ rails routes
api_offices   GET      /api/offices(.:format)    api/offices#index                                                                       
POST   /api/offices(.:format)    api/offices#create 
```

Hcn 112 【a 1 】事業所コントローラ作成

---

app/models/user.rb

[link](https://dev.classmethod.jp/articles/pull-request-template/)
* https://example.com
userモデルに二重にかかっていたバリデーションを修正
なし
なし
なし
なし
emailのユニーク制約が二重にかかっていたため、ユニークを電話番号に修正
修正
https://gyazo.com/0447b97967444970ddb98ed61839fc14

update: validation

---

app/controllers/api/specialists/staffs_controller.rb
app/models/office.rb
app/models/staff.rb
db/migrate/20220518035139_create_staffs.rb
db/migrate/20220518050442_create_active_storage_tables.active_storage.rb

* スタッフのモデル・コントローラ・カラム作成
* スタッフと事業所の関係性を定義（スタッフは事業所を兼務でき、事業所は複数のスタッフを持つため、多対多）
* Active Storageインストール
* スタッフモデルとActive Storageの紐付け
[Railsガイド Active Storage の概要](https://railsguides.jp/active_storage_overview.html)
```
・開発環境だとローカルストレージ、本番環境だとAmazon S3や Google Croud Storageなどの
クラウドストレージサービスへのファイルアップロードを提供している
・画像のリサイズができる(variantメソッド)
・レコード(モデル)とファイルの間に1対1、1対多などと関係を設定できる
```
【手順で参考にした記事】
[Active Storageの基本情報と実装方法](https://prograshi.com/framework/rails/active-storage/)
* アクションの作成（これからやります）
* なし
* なし
- `docker-compose restart`実行
* `rails db:migrate` 後、`rails db:migrate:status`
```
up     20220510060242 …
```

スタッフモデル・コントローラ作成　ActiveStorageインストール

---

app/controllers/api/overrides/specialist_registrations_controller.rb
app/models/specialist.rb
app/models/user.rb
config/routes.rb

ケアマネージャーのルーティング修正
・devise_scopeの設定
`devise scope　:user→ devise_scope :specialist`
に変更
・変更に伴い、specialistsモデルの作成
・specialistsにネストされているルーティングもコントローラーを指定し動作するよう設定
なし
なし
なし
```
docker compose exec web bash
rails routes
```
**今回のルーティングの変更で関連あるものの動作を確認してます**
ブランチ変更
`git fetch
git checkout remotes/origin/feature/specialists-routing`
①ケアマネ新規会員登録
1.PostmanからPost localhost:3000/api/specialists/users にリクエストを送る
```
name: 任意
email: 任意
password: password
password_confirmation: password
post_code: 任意
address: 任意
phone_number: 任意
confirm_success_url: localhost:8000
```
2.メールキャッチャーにスペシャリストと書かれたメールが飛んでくる
・動画手順
https://www.loom.com/share/8dbdae816d4f4f619de9b51b77fb054b
②ユーザーログインログアウト
動作確認
1. ログイン　ポストマンから`post http://localhost:3000//api/login`にリクエスト送る
email
password …

fix: routes

---

config/environments/production.rb
config/initializers/cors.rb
heroku.yml

1. 本番環境用にcorsの設定
最新のdevelopではない
新規登録などmailerがカラムものはできない
1. 本番環境のFRONTからリクエストを受け取れる
なし
1. 下記のプルリクの手順通りすすめる
2. 確認手順も下記のプルリクに従う
[FRONTプルリク](https://github.com/koki-takishita/home-care-navi-front/pull/96)
* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

API・本番環境 cors設定

---

app/controllers/api/specialists/staffs_controller.rb
config/routes.rb

1. スタッフ削除機能実装
- なし
- スタッフの削除ができる
- なし
- 
- room手順参照  動画見てください
```ruby
git fetch && git checkout origin/feature/staff-destroy
```
- Postmanコピペ用
```
http://localhost:3000/api/specialists/offices/1/staffs/
```
https://www.postman.com/
[手順動画](https://www.loom.com/share/0f758d3f2a494c04a41c246e8751e916)
- レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

build: staff destroy

---

app/controllers/api/offices/appointments_controller.rb
app/controllers/api/offices_controller.rb
app/controllers/api/specialists/offices_controller.rb
app/controllers/api/specialists/staffs_controller.rb
app/models/appointment.rb
app/models/office.rb
app/models/user.rb
config/routes.rb
db/migrate/20220615050702_create_appointments.rb
db/schema.rb

- このプルリクで何をしたのか？
1. WEB予約機能実装
2. ケアマネ事業所コントローラ　showメソッド実装
3. 既存のコントローラの修正
- なし
- WEB予約ができるようになる
- なし
- 
[テーブル定義書](https://docs.google.com/spreadsheets/d/15AbCnOzcFlnN8CO-sXxKM6bMS7VtExbew-FpYHav91Q/edit#gid=1771130073)
```ruby
git fetch && git checkout origin/feature/appointments-create
```
- コンテナリスタート
```ruby
```
- コンテナ入る
```ruby
```
- マイグレート
```ruby
```
- マイグレートステータス確認
```ruby
```
- カラム名確認
```ruby
Appointment.column_names
```
- 予約完了したときのデータ

WEB予約機能　今まで作ったコントローラの修正

---

app/controllers/api/specialists/appointments_controller.rb
app/models/appointment.rb
config/routes.rb
db/seeds.rb

- 予約状況確認機能実装
- 予約のダミーデータをseedで作成できるようにした
- 予約モデルの関連付け修正
- 予約履歴画面の表示崩れの修正（できれば今週対応。できなければ来週までに対応）
- ケアマネが、APIを叩けば予約状況を確認できる
- rails db:resetができなくなる
```ruby
git fetch && git checkout origin/feature/appointments-seed
```
- コンテナリスタート
```ruby
```
- コンテナ入る
```ruby
```
- seed実行
```ruby
rails db:seed
```
- コンソール入り、予約データ確認
```ruby
rails c
```
```ruby
Appointment.all
```
- フロントで、ユーザーとしてログインする
http://localhost:8000/users/login
```ruby
customer0@example.com
password
```
- ヘッダーから予約履歴画面に遷移し、予約履歴があるか確認する（PC版で履歴が縦に並んでしまいますが、後で修正します。）
- フロントでケアマネとしてログインをする
http://localhost:8000/specialists/login
```ruby
specialist3@example.com
password
```
- Postmanで予約状況を確認する
```ruby
http://localhost:3000/specialists/offices/<事業所ID>/appointments
``` …

予約状況確認機能実装 予約seed作成

---

app/controllers/api/customer/thanks_controller.rb
app/models/thank.rb
config/locales/ja.yml

- お礼のバリテーション修正
- なし
一人のカスタマーが同じスタッフにお礼しようとすると、バリテーションエラーになる
- なし
- fetch and checkout 下記プルリクに動作手順を記述
https://github.com/koki-takishita/home-care-navi-front/pull/180
```ruby
git fetch && git checkout origin/feature/create-thank
```
- レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

お礼api バリテーション設定

---

app/controllers/api/specialists/care_recipients_controller.rb
app/controllers/api/specialists/staffs_controller.rb

- 下記の機能の、ページごとのデータの絞り込み機能と、更新日によるデータの並び替えを実装
- スタッフ一覧
- 利用者一覧
- なし
```ruby
git fetch && git checkout origin/technical/staffs-care_recipients-index-sort
```
```ruby
git fetch && git checkout origin/technical/staffs-care_recipients-index-pagenation
```
- スタッフをseedで作る（即席でコードを変更して、今回のプルリクの都合の良いように作ります。**終わったらもとに戻してください**）
- **db/seeds/dummy_staffs.seeds.rb**を、下記のように変更
```ruby
.
.
def create_staffs(office: , count: 30)
office.staffs.destroy_all
count.times{
name = Faker::Name.name
image = build_image
office.staffs.create!(
name: name,
kana: name.yomi,
introduction: "#{office.name}の#{name}です。素晴らしいスタッフです。",
image: image
)
}
end
.
.
def create_office_staffs
office = Specialist.first.office
create_staffs(office: office)
end
.
.
```
- コンテナ入る
```ruby …
```

スタッフ・利用者一覧　ページごとのデータの絞り込み　ソート

---

app/controllers/api/customer/bookmarks_controller.rb
app/controllers/api/customer/offices_controller.rb

- 事業所一覧のデータから、各事業所に紐づくログイン済みユーザーのブックマークデータを取得
- なし
```ruby
git fetch && git checkout origin/feature/bookmark-create-destroy
```
```ruby
git fetch && git checkout origin/feature/submit-destroy-bookmark
```
- コンテナ内に入り、すべてのテストを実行。すべてパスすればOK
```ruby
```
```ruby
bundle exec rspec spec/requests/
```
実行結果
```ruby
Finished in 1.93 seconds (files took 4.53 seconds to load)
14 examples, 0 failures
```
- こちらのプルリクの確認をお願いします
https://github.com/koki-takishita/home-care-navi-front/pull/197
- なし
- build
```ruby
docker-compose build
```
- コンテナリスタート
```ruby
```
- コンテナ入る
```ruby
```
- コンソール入る
```ruby
rails c
```

事業所一覧画面でブックマークデータ取得

---

app/controllers/api/customer/offices_controller.rb

1. スタッフを並び替え、お礼が多い順に並び替える
- 手順はすべてこちらに書いてあります。
https://github.com/koki-takishita/home-care-navi-front/pull/200
- 参考サイト
[関連付け多い順に並べるやつ](https://stress-hack.fun/%E9%96%A2%E9%80%A3%E3%81%99%E3%82%8B%E3%83%AC%E3%82%B3%E3%83%BC%E3%83%89%E6%95%B0%E3%81%8C%E5%A4%9A%E3%81%84%E9%A0%86%E3%81%AB%E4%B8%A6%E3%81%B3%E6%9B%BF%E3%81%88%E3%82%8B/)

お礼が多い順になるように修正

---

spec/models/user_spec.rb

- モデルテストでエラーが出ていたものを正しく通るように修正
- なし
```ruby
git fetch && git checkout origin/technical/pre-commit-rspec
```
- コンテナに入り、すべてのテストを実行する
```ruby
```
```ruby
bundle exec rspec
```
実行結果
```ruby
Finished in 2.19 seconds (files took 4.05 seconds to load)
17 examples, 0 failures
```
- `.git/hooks`内に新しく`pre-commit`という名前のファイルを作る
-  実行権限を与えるため、下記コマンドを実行
```ruby
chmod a+x .git/hooks/pre-commit
```
- 下記のコードを追加する
```ruby
#!/bin/sh
if git diff --cached --name-only --diff-filter=AM | grep '\.rb$'; then
echo '---Rspecが通るかチェック---'
docker-compose exec -T web bundle exec rspec
fi
```
[Docker環境でもGitのcommitやpushの前にRubocopのチェックをする](https://zenn.dev/yamat47/articles/a9b0b4d937ce03b695e9)
- コメントアウトしてる部分を解除すれば、コミット時にrubocopが走るようになります。ただ、400箇所くらい引っかかるのでコミットできなくなります …

モデルテスト通るように修正　コミット時テスト走る（各自設定）

---

app/controllers/api/customer/thanks_controller.rb
spec/requests/api/customer/thanks_spec.rb

- 関連付け(staff, office)も含むように設定
- なし
```ruby
git fetch && git checkout origin/fix/thank-show
```
- 同じ手順でpostmanでリクエストして、officeのnameとstaffのnameが取得できることを確認する
https://github.com/koki-takishita/home-care-navi-api/pull/101
[![Image from Gyazo](https://i.gyazo.com/c30dd98d510a486a875b152a2dd1295e.png)](https://gyazo.com/c30dd98d510a486a875b152a2dd1295e)
[as_json概要](https://railsdoc.com/page/as_json)
[ソースコードのaj_jsonの例を参照](https://github.com/rails/rails/blob/984c3ef2775781d47efa9f541ce570daa2434a80/activemodel/lib/active_model/serializers/json.rb#L96)
```ruby
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
```

お礼詳細関連付け設定

---

app/controllers/api/specialists/thanks_controller.rb
app/models/thank.rb
config/routes.rb

1. ケアマネお礼のリスト取得
- request spec
```ruby
git fetch && git checkout origin/feature/thank-list-to-specialist
```
`Postmanで動作確認を行う`
1. お礼が存在するケアマネを探す
```ruby
docker-compose exec web rails c
Thank.first.office.user.email
```
2. 1で取得したemaiでログ・イン処理する(postman)
3. お礼の履歴を取得する ※pramsにpage=0を指定(ページネーション用)
```ruby
http://localhost:3000/api/specialists/offices/thanks?page=0
```
4. 下記のリクエストが返ってこればok
```ruby
{
"thanks": [
{
"id": 50627,
"user_id": 2875,
"office_id": 22083,
"staff_id": 76822,
"comments": "神野 光さんは素晴らしいケアマネージャーです。",
"created_at": "2022-07-26T22:23:30.617+09:00",
"updated_at": "2022-07-26T22:23:30.617+09:00",
"staff": {
"id": 76822,
"name": "神野 光",
"kana": "かみの ひかり",
"introduction": "サンプルオフィス-2の神野 光です。素晴らしいスタッフです。",
"created_at": "2022-07-05T08:19:11.567+09:00", …
```

ケアマネお礼のリスト取得

---

spec/requests/api/customer/bookmarks_spec.rb

- ブックマーク解除のテストを追加
- ログインモジュール化に伴い重複しているコードの削除
- なし
```ruby
git fetch && git checkout origin/test/bookmark-destroy
```
- すべてのテストが通るか確認する
```ruby
docker-compose exec web bundle exec rspec
```
実行結果
```ruby
Finished in 5.09 seconds (files took 5.97 seconds to load)
24 examples, 0 failures
```
タッキーのお礼テスト
- build
```ruby
docker-compose build
```
- コンテナリスタート
```ruby
```
- コンテナ入る
```ruby
```
- コンソール入る
```ruby
rails c
```

ブックマーク解除のテスト作成

---

spec/requests/api/specialist/offices_spec.rb

- 事業所登録のRequest Specについて、下記を実施
- ログインモジュール化に伴い重複しているコードの削除
- テスト項目「同じケアマネが複数事業所を登録できない」を追加
- 画像登録ができているかチェックするときの`images_blobs.blank?`を`images.attached?`に変更
- HTTPステータスコードのマッチャーを追加
- なし
```ruby
git fetch && git checkout origin/test/office-refactoring
```
- コンテナ内に入り、テスト実行
```ruby
bundle exec rspec spec/requests/api/specialist/offices_spec.rb --format documentation
```
実行結果
```ruby
Api::Specialists::Offices
ログイン済み
スペシャリスト
事業所を登録できる
事業所を複数登録できない
カスタマー
事業所を登録できない
ログインしていない
事業所を登録できない
Finished in 2 seconds (files took 5.84 seconds to load)
4 examples, 0 failures
```
タッキーのお礼テスト
- build
```ruby
docker-compose build
```
- コンテナリスタート
```ruby
```
- コンテナ入る
```ruby
```
- コンソール入る
```ruby
rails c
```

事業所登録 Request Spec リファクタリング テスト項目追加

---

app/controllers/api/customer/histories_controller.rb
app/models/history.rb
app/models/office.rb
app/models/user.rb
db/migrate/20220801023101_create_histories.rb
db/schema.rb
spec/factories/histories.rb

- 閲覧履歴のモデル・コントローラ・マイグレーションファイルの作成
- モデル同士の関連付け
- なし
```ruby
git fetch && git checkout origin/feature/create-history-model-controller
```
- コンテナ内に入る
```ruby
```
- migrationファイルの内容をDBに反映する
```ruby
```
- マイグレーションの状態を確認する
```ruby
```
- 下記のようになていればOK
```ruby
database: api_development
up     20220517052740  Add selected flags to offices
up     20220518035139  Create staffs
up …
```

閲覧履歴モデル・コントローラ・マイグレーションファイル作成

---

app/controllers/api/customer/thanks_controller.rb
app/models/thank.rb
config/locales/ja.yml
db/migrate/20220801021247_add_column_to_thank.rb
db/schema.rb
spec/factories/thanks.rb
spec/requests/api/customer/thanks_spec.rb

1. お礼テーブルにカラム追加
- name (お礼する人の名前)
- age (お礼する人の年齢)
2. ロケール設定
3. バリテーション設定
4. カラム追加するとテスト失敗するので追加に対応するように修正
- なし
```ruby
git fetch && git checkout origin/feature/thank-model-add-column
```
```ruby
docker-compose exec web rails db:migrate
```
- db/schema.rbを開いて`thanksの定義`が画像の様になっている
```ruby
create_table "thanks", force: :cascade do |t|
t.bigint "user_id", null: false
t.bigint "office_id", null: false
t.bigint "staff_id", null: false
t.string "comments", null: false
t.datetime "created_at", null: false
t.datetime "updated_at", null: false
t.string "name", limit: 30, null: false
t.integer "age", null: false
t.index ["office_id"], name: "index_thanks_on_office_id"
t.index ["staff_id"], name: "index_thanks_on_staff_id"
t.index ["user_id", "office_id", "staff_id"], name: …
```

お礼テーブルにカラム追加

---

config/routes.rb

- 手順はフロントのプルリクに従う
https://github.com/koki-takishita/home-care-navi-front/pull/230

パスワードリセットルーティング設定

---

config/routes.rb

1. ケアマネ側のパスワードようのルーティング設定
- 手順は↓のプルリクに従う
https://github.com/koki-takishita/home-care-navi-api/pull/123

ケアマネ側パスワード設定

---

config/environments/production.rb

- 本番環境で使用するメール情報を環境変数化
- メールアカウント確保しました
- gmailで捨てアド用意するの試しましたが、結構大変なので、まずは自分のprumアドレスを使用します
- なし
- Slackに添付のloom動画参照
[ActionMailerの使い方メモ@heroku](https://qiita.com/tkc310/items/7aa476ef541b755af4ca)

メールのuser_nameとpasswordを環境変数化

---

app/controllers/api/overrides/customer/registrations_controller.rb
config/routes.rb

ユーザー編集機能 インデント修正

---

spec/requests/api/specialist/staffs_spec.rb

- スタッフ編集・削除のリクエストスペック作成
- 変数名をRubyの命名規約にしたがって一部変更
- サンプル画像`@sampleImage`を`@sample_image`に変更
- なし
```ruby
git fetch && git checkout origin/test/request-spec-staff-update-destroy
```
- スタッフのリクエストスペックの全部のテストを実行する
```ruby
docker-compose exec web bundle exec rspec spec/requests/api/specialist/staffs_spec.rb --format documentation
```
実行結果
```ruby
Api::Specialists::Staffs
ログイン済み
スペシャリスト
スタッフを登録できる
スタッフを編集できる
スタッフを削除できる
ログインしていない
スタッフを登録できない
Finished in 1.31 seconds (files took 3.9 seconds to load)
4 examples, 0 failures
```
- なし
```javascript
NG
```
```ruby
```
```ruby
docker-compose exec web bundle …
```

スタッフ編集・削除のリクエストスペック作成

---

app/controllers/api/customer/bookmarks_controller.rb
app/models/bookmark.rb
app/models/office.rb

- ブックマークコントローラのリファクタリング
- オフィスに紐づくデータを取得するメソッドをモデルファイルに移行
- なし
```ruby
git fetch && git checkout origin/fix/refactoring-bookmark-controller
```
```ruby
git fetch && git checkout origin/fix/appointments-index-display-img
```
- ブックマーク、予約一覧画面に遷移したときに正しくデータが表示されているか
- 画像なしオフィス、画像ありオフィス
- お礼なしオフィス、お礼ありオフィス
- [Railsのpresenceメソッドの使い方を現役エンジニアが解説](https://techacademy.jp/magazine/20210)
```javascript
NG
```
```ruby
```
```ruby
```

ブックマークコントローラのリファクタリング

---

app/controllers/api/check_controller.rb
app/models/office_detail.rb
spec/factories/offices.rb

- Rubocopでのインデント修正
・オフィス関連ファイルをRubocopで確認・修正
　インデント・スペースの調整
- Rubocop修正指摘箇所で 他担当者のファイル 修正・加筆
```ruby
git fetch && git checkout origin/fix/office-rubocop-check
```
- [全Rspecテストをクリアできるか確認する](https://gyazo.com/5a743793b280d407b5d0845134161b6c)
```ruby
docker-compose exec web bundle exec rspec 
```
[テーブル定義書](https://docs.google.com/spreadsheets/d/15AbCnOzcFlnN8CO-sXxKM6bMS7VtExbew-FpYHav91Q/edit#gid=1771130073)
なし
```javascript
NG
```
```ruby
```
```ruby
docker-compose exec web bundle …
```

Rubocop修正：事業所関連ファイル

---

.github/workflows/rails_ci.yml
docker-compose.yml

- RspecをGitHubActionsで実行する
- 下記のブランチにプッシュしたときや、プルリクを上げたときにRspecが実行される
- `main`
- `develop`
- なし
- `Ruby / Rspec_test (pull_request) `が、今回作成したもの
- テストが通らないとバツマークがつき、マージできないようになる
- テストを実行しているのはここ
- [RailsアプリCICDパイプライン構築の手順（備忘録）（Docker+Rspec+GitHubActions+heroku）](https://qiita.com/nofate8785/items/09d1d20c518aa6c55287)
```javascript
NG
```
```ruby
```
```ruby
```

RspecをGitHubActionsで実行する

---

config/environments/test.rb
spec/requests/api/customer/bookmarks_spec.rb
spec/requests/api/customer/histories_spec.rb
spec/requests/api/customer/thanks_spec.rb
spec/requests/api/specialist/offices_spec.rb
spec/requests/api/specialist/signup_login_spec.rb
spec/requests/api/specialist/staffs_spec.rb
spec/spec_helper.rb
spec/support/login_support.rb

- ケアマネ新規登録~ログイン コントローラテスト作成
- なし
```ruby
git fetch && git checkout origin/test/specialist-signup-login
```
- テスト実行
```ruby
docker-compose exec web bundle exec rspec spec/requests/api/specialist/signup_login_spec.rb --format documentation
```
実行結果
```ruby
Api::Specialists
ケアマネ
新規登録できる
ログインできる
登録済みカスタマー
ログインできない
Finished in 0.94035 seconds (files took 3.66 seconds to load)
3 examples, 0 failures
```
- [Railsでテストするためにデフォルトの「www.example.com」ドメインを変更するにはどうすればよいですか?](https://stackoverflow.com/questions/598933/how-do-i-change-the-default-www-example-com-domain-for-testing-in-rails)
```javascript
NG
```
```ruby
docker-compose exec web bundle exec rubocop --auto-correct …
```

ケアマネ新規登録~ログイン コントローラテスト作成

---

spec/requests/api/customer/signup_login_spec.rb

- カスタマー新規登録~ログイン コントローラーテスト作成
- なし
```ruby
git fetch && git checkout origin/test/customer-signup-login
```
- テスト実行
```ruby
docker-compose exec web bundle exec rspec spec/requests/api/customer/signup_login_spec.rb --format documentation
```
実行結果
```ruby
Api::Customer
カスタマー
新規登録できる
ログインできる
登録済みケアマネ
ログインできない
```
- なし
```javascript
NG
```
```ruby
```
```ruby
```

カスタマー新規登録~ログイン コントローラーテスト作成

---

app/models/user.rb
config/initializers/devise.rb
spec/models/user_spec.rb

- ユーザーモデルテスト作成
- ユーザーテーブルの各カラムに足りないバリデーション追加
-  フォーマットチェック、文字数制限
- なし
```ruby
git fetch && git checkout origin/test/user-model-test
```
- テスト実行
```ruby
docker-compose exec web bundle exec rspec spec/models/user_spec.rb --format documentation 
```
実行結果
```ruby
Userモデルのテスト
アソシエーションのテスト
Officeモデルとの関係
1:1となっている
Appointmentモデルとの関係
1:Nとなっている
Thankモデルとの関係
1:Nとなっている
Bookmarkモデルとの関係
1:Nとなっている
Historyモデルとの関係
1:Nとなっている
バリデーションのテスト
すべての項目の値が正しい場合、有効である
名前がない場合、無効である
名前が31文字以上の場合、無効である
メールアドレスがない場合、無効である
メールアドレスが256文字以上の場合、無効である
メールアドレスのフォーマットが適切でない場合、無効である
メールアドレスが重複している場合、無効である
パスワードがない場合、無効である
パスワードが8文字未満である場合、無効である
パスワードが33文字以上である場合、無効である
パスワードのフォーマットが適切でない場合、無効である
電話番号がない場合、無効である
電話番号のフォーマットが適切でない場合、無効である
電話番号が重複している場合、無効である
郵便番号がない場合、無効である
郵便番号のフォーマットが適切でない場合、無効である …
```

ユーザーモデルテスト作成

---

app/models/office.rb
config/locales/ja.yml
db/migrate/20220824004928_add_uniq_index_to_fax_number_and_phone_number.rb
db/schema.rb
lib/tasks/office_fax_number.rake
spec/requests/api/specialist/offices_spec.rb

1. fax_number 空のときバリテーションスキップするように修正
2. I18n設定 `ファックス`から`FAX番号`へ変更
3. unique制約追加(user_id, fax_number, phone_number) ※ rubocopに警告されたため
4. すでにデータベースで重複しているfax_numberを削除するjob作成
- 作成したrakeタスクはfax_numberのみチェックしているので、phone_numberとuser_idの重複は見てないので、かぶったら消してください
- rubocop `Naming/VariableNumber` と `Naming/VariableName`の修正 ※ 参考サイト参照 `spec/requests/api/specialist/offices_spec.rb`
-  カラム名に指摘受けているので
```ruby
❯ rubocop spec/requests/api/specialist/offices_spec.rb
Inspecting 1 file
C
Offenses:
spec/requests/api/specialist/offices_spec.rb:10:5: C: Naming/VariableName: Use snake_case for variable names.
@sampleImage = Rack::Test::UploadedFile.new(File.join(Rails.root, 'spec/fixtures/island.png'), 'image/png')
^^^^^^^^^^^^
spec/requests/api/specialist/offices_spec.rb:10:49: C: Rails/FilePath: Prefer …
```

fax_number空の時、バリテーションスキップできないbug改修

---

app/models/contact.rb
spec/factories/contacts.rb
spec/factories/staffs.rb
spec/models/contact_spec.rb

- 問い合わせのモデルテスト 8項目
- API側でのバリデーション設定
文字数やemailフォーマットチェック
- typo修正 (＋１ファイル)
- なし
```ruby
git fetch && git checkout origin/test/contact-model-test
```
- 該当ファイルのRspecテストを実施する
```ruby
docker-compose exec web bundle exec rspec spec/models/contact_spec.rb --format documentation
```
実行結果
```ruby
Contactのモデルテスト
バリデーションテスト
すべての項目の値が正しい場合、有効である
名前がない場合、無効である
名前が31文字以上場合、無効である
メールアドレスがない場合、無効である
メールアドレスが256文字以上場合、無効である
メールアドレスのフォーマットが適切でない場合、無効である
利用者区分がない場合、無効である
お問い合わせ内容がない場合、無効である
Finished in 0.93523 seconds (files took 4.92 seconds to load)
8 examples, 0 failures
```
[テーブル定義書](https://docs.google.com/spreadsheets/d/15AbCnOzcFlnN8CO-sXxKM6bMS7VtExbew-FpYHav91Q/ed …

問い合わせ　モデルテスト

---

db/seeds/dummy_customer.seeds.rb

- カスタマー専用seedファイルを実行するときに、**電話番号は不正な値です**というバリデーションエラーが出て、ダミーデータを作成できなかった不具合修正
- `db/dummy_files/dummy.csv`内の5000件のデータすべてを修正するのは骨が折れるため、電話番号を乱数で生成するようにしました
- 今回変更したファイルのRubocop 自動修正
- なし
```ruby
git fetch && git checkout origin/fix/dummy_customer.seeds.rb
```
- seed実行
```ruby
docker-compose exec web rails db:seed:dummy_customer
```
```ruby
Time: 00:00:40 |===============================================>>| 100% Progress
```
- なし
```javascript
NG
```
```ruby
```
```ruby
```

カスタマー専用seedファイルをエラーなく実行できるように修正

---

spec/models/thank_spec.rb

- お礼モデルテスト作成
- モデル同士の関連付けのテスト
- バリデーションのテスト
- 必須項目
- 文字数
- 同じスタッフにお礼を作成できない
- なし
```ruby
git fetch && git checkout origin/test/thank-model-test
```
- テストを実行する
```ruby
docker-compose exec web bundle exec rspec spec/models/thank_spec.rb --format documentation
```
[テスト仕様書](https://docs.google.com/spreadsheets/d/12xMuHo1K8Fd7FIB7rqeioxdWmrWw7aYK4QZ_Clsfk5Q/edit#gid=1789577746)
- なし
```javascript
NG
```
```ruby
```
```ruby
```

お礼モデルテスト作成

---

spec/requests/api/customer/offices_spec.rb

- オフィスのキーワード検索のコントローラーテスト作成
- `params`の`keywords`に住所の一部を入れて検索し、狙った値が取得できているか
- `params`の`postCodes`に郵便番号を入れて検索し、狙った値が取得できているか
- 存在しない郵便番号で検索するテスト
```ruby
git fetch && git checkout origin/test/search_office_keyword-request_spec
```
- テスト実行
```ruby
docker-compose exec web bundle exec rspec spec/requests/api/customer/offices_spec.rb --format documentation
```
```ruby
Api::Customer::Offices
エリア検索機能
登録済みデータ
東京都千代田区
取得できるのは最大10件
オフセット
5件取得できる
ヒットしない
新潟県佐渡市
5件取得できる
北海道旭川市
5件取得できる
沖縄県那覇市
5件取得できる
キーワード検索
東京都
取得できるのは最大10件
千代田区
取得できるのは最大10件
丸の内
3件取得できる
丸の内1丁目
1件取得できる
東京都千代田区丸の内のオフィスの郵便番号
1件取得できる
東京都千代田区丸の内のオフィスの住所と郵便番号
1件取得できる
登録されていないデータ
静岡県浜松市
ヒットしない
東京都港区
ヒットしない
新潟県新潟市
ヒットしない
北海道札幌市
ヒットしない
沖縄県石垣市
ヒットしない
キーワード検索
静岡県
ヒットしない
浜松市
ヒットしない
Finished in 7.06 seconds (files took 6.11 …
```

オフィスのキーワード検索のコントローラーテスト作成
